### ISSUE TITLE
Is this a duplicate repo?

### ISSUE THREAD

**Issue by gep13** [akordowski/Cake.Compression#1]
https://github.com/frozenskys/cake-compression

Was just wondering if you had seen the above?  Is it a duplicate?

Thanks!

**Comment by akordowski** [comment]
The other repo seems to be a fork of my repo. The following [commit](https://github.com/frozenskys/cake-compression/commit/1584b8a71c1598a956b7809976fc7a641dd8b5c1) indicates that.

**Comment by gep13** [comment]
Agreed.

@frozenskys was there a reason that you did a hard fork of this project, rather than extend it through Pull Requests?  I am just a little worried about duplication of effort, and confusion as to which addin to use.

Thanks!

**Comment by frozenskys** [comment]
@gep13 - Just due to stupidity on my part - guess getting back to open source coding after several years locked in the Closed Source\TFS world is more difficult than I would have liked. I have deleted my hard fork, and I'm sorry for the confusion.

**Comment by gep13** [comment]
@frozenskys thanks for getting back to me, I appreciate it.  Any effort to get involved in Open Source should be welcomed, and I am sure that @akordowski will appreciate any help that you can offer on this addin.  I just wanted to make sure that going forward, there wasn't any duplication of effort, which would be better served in creating a single addin that has the benefit of multiple people working on it.

If you have any questions about anything related to Cake, and Open Source in general, feel free to reach out, I love talking about all this stuff 😄

**Comment by frozenskys** [comment]
@gep13 😄 Thanks - Cake is awesome - I have pretty much sold our entire dev team on it. Have some questions about extending the Team Foundation plugin (cake-vso) and some other TFS Build cake related stuff - where's the best place to talk about this?

**Comment by gep13** [comment]
@frozenskys that is great news!  Perhaps best to start questions/issues about cake-vso by raising an issue here: https://github.com/cake-build/cake-vso and for any general questions either create a question on StackOverflow (tagged with `cakebuild` http://stackoverflow.com/questions/tagged/cakebuild) or reach out on our Gitter channel: https://gitter.im/cake-build/cake.

**Comment by gep13** [comment]
@akordowski closing to close this issue, thanks!
