### ISSUE TITLE
Error: Failed to install addin 'Cake.Compression'.

### ISSUE THREAD

**Issue by tidusjar** [akordowski/Cake.Compression#13]
Hello,

I've all of the sudden just got the following error

```Error: Failed to install addin 'Cake.Compression'.```

Build info: https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.2965

**Comment by akordowski** [comment]
I have updated the AddIn to Cake 0.26.1. There are some breaking changes in this Cake version. My suggestion is to pin the AddIn version to the 0.1.4 version: `#addin nuget:?package=Cake.Compression&version=0.1.4` The new NuGet package version is 0.1.5.

**Comment by andreas271828** [comment]
The suggested workaround is leading to further errors for me:
`Error: The assembly 'Cake.Compression, Version=0.1.4.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)`

**Comment by akordowski** [comment]
It seems to be a Cake issue. I've tested it and the AddIn is properly installed, but raises an exception anyway. As woraround please use `--settings_skipverification=true` to execute yout Cake script.

**Comment by akordowski** [comment]
The problem is fixed and a new version 0.1.6 is available.
