### ISSUE TITLE
Suggestion: Consider targeting net5.0, netstandard2.0, and net461

### ISSUE THREAD

**Issue by augustoproiete** [akordowski/Cake.Compression#27]
Hello @akordowski! :relaxed:

I noticed your addin only targets `netstandard2.1` at the moment, which makes it impossible to use with the .NET Framework runner.

If possible, add at `netstandard2.0` at a minimum, and bonus points if you can also add `net5.0` and `net461`. Below are the current [recommendations](https://cakebuild.net/docs/extending/addins/best-practices#net-target-version) for Cake addins, for reference.

[![image](https://user-images.githubusercontent.com/177608/108643659-e1090500-7481-11eb-81cf-1e287b93d78d.png)](https://cakebuild.net/docs/extending/addins/best-practices#net-target-version)

**Comment by akordowski** [comment]
Thank you for your suggestion @augustoproiete!
That is a good idea. A new package is released.

**Comment by augustoproiete** [comment]
Awesome! Thanks @akordowski! :+1:
