### ISSUE TITLE
Missing `ICSharpCode.SharpZipLib` dependency?

### ISSUE THREAD

**Issue by dennisroche** [akordowski/Cake.Compression#3]
Hi, 

I'm having difficulty using `Cake.Compression` in our build. 

The `.cake` file. 

```
// Using Cake (C# Make) http://cakebuild.net

#addin "Cake.Compression"
#tool "nuget:?package=SharpZipLib"
```

Gives the error message,

```
Error: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified.
```

I tried to resolve it by adding the `#tool "nuget:?package=SharpZipLib"` reference to no avail.

**Comment by dennisroche** [comment]
The `SharpZipLib` package is downloaded by nuget correctly, under the `tools\Addins` directory. 

```
+---Addins
|   +---Cake.Compression
|   |   \---lib
|   |       \---net45
|   \---SharpZipLib
|       \---lib
|           +---11
|           +---20
|           +---SL3
|           \---SL4
+---Cake
```

Extracting the `Cake.Compression.nupkg`, I can verify that the dependency is specified correctly in the `.nuspec`. 

I'm have been able to workaround the issue by copying the `ICSharpCode.SharpZipLib.dll` to the `Addins\Cake.Compression\lib\net45`

```
// Hack: Cake.Compression is missing local copy of SharpZipLib dependencies
if (!FileExists("./tools/Addins/Cake.Compression/lib/net45/ICSharpCode.SharpZipLib.dll")) {
    CopyFile("./tools/Addins/SharpZipLib/lib/20/ICSharpCode.SharpZipLib.dll",
        "./tools/Addins/Cake.Compression/lib/net45/ICSharpCode.SharpZipLib.dll");
}
```

**Comment by akordowski** [comment]
Thanks for your feedback and the detailed informations. I will took a look into it later this week and then get back to you.

**Comment by akordowski** [comment]
@Sam13 Thank you for the hint. I wasn't aware of that.
